version: '3'

services:
  mcp-image-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-image-recognition-dev
    # env_file can be used instead of environment section:
    # env_file: .env
    environment:
      - VISION_PROVIDER=${VISION_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_OCR=${ENABLE_OCR:-false}
    volumes:
      - ./src:/app/src  # For development - map source code
      - ./tests:/app/tests  # For running tests
      # Add your local directories here for image access
      # - ~/Pictures:/images
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
